version: '3.4'

services:
  socketchat:
    image: socket-chat
    container_name: socket-chat
    build:
      context: ./socketChat
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 0.0.0.0:4000:4000
    restart: always

  
