version: '3.4'

services:
  weChatSockerChat:
    image: we-chat-socket-chat
    container_name: weChatSockerChat
    build:
      context: ./WeChat.Socket
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 0.0.0.0:4000:4000
    restart: always

  
