version: '3.4'

services:
  weChatSocket:
    image: wechat-socketchat
    container_name: weChatSocket
    build:
      context: ./WeChat.Socket
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 0.0.0.0:4000:4000
    restart: always
    
  weChatWebUi:
    image: wechat-webui
    container_name: weChatWebUi
    build:
      context: ./WeChat.Ui
      dockerfile: Dockerfile
    ports:
      - 4100:80
    restart: always 

  
